version: '3'
services:
  app:
    container_name: nuxt
    image: node:10-alpine
    tty: true
    environment:
      - HOST=0.0.0.0
    ports:
      - "30:3000"
    working_dir: '/app'
    volumes:
      - "./app:/app"
    entrypoint: yarn dev