version: '3'
services:
  app:
    container_name: nuxt
    image: node:10-alpine
    tty: true
    environment:
      - HOST=0.0.0.0
    ports:
      - $PORT:3000
    working_dir: /app
    volumes:
      - $APP_PATH:/app
      - ./init.sh:/init.sh
    entrypoint: /bin/ash /init.sh